---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "deploying Backend Database"
spec:
  selector:
    matchLabels:
      app: application
      environment: dev
  template: 
    metadata:
      labels:
        app: application
    spec:
      containers: 
      - name: app-container
        image: anildoc143/privaterepo_websites:app
        ports:
          - containerPort: 8080
        imagepullsecrets:
          - name: mydockerhub-secret
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "350Mi"
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -f http://localhost:8080/health || exit 1"]
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 30
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -f http://localhost:8080/health || exit 1"]     
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 30

    
              
