---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: dev
spec:
  selector:
    app: application
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: application
