---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: dev
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql
